import { openDatabase } from "../database/connection.js";
import { ServiceRequest } from "../models/ServiceRequest.js";

export class ServiceRequestRepository {
  // opens its own connection; omitting dbPath falls back to the default database
  constructor(dbPath) {
    this.db = openDatabase(dbPath);
    this.initialize();
  }

  close() {
    this.db.close();
  }

  // no need to call this method outside the class; its in the constructor
  // stores only resident_id; Resident information stays in the residents table
  initialize() {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS service_requests (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        resident_id INTEGER NOT NULL,
        service_type TEXT NOT NULL,
        description TEXT NOT NULL,
        date_requested TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'Pending'
      )
    `);
  }

  // converts a database row into a ServiceRequest instance
  toServiceRequest(row) {
    return new ServiceRequest({
      id: row.id,
      residentId: row.resident_id,
      serviceType: row.service_type,
      description: row.description,
      dateRequested: row.date_requested,
      status: row.status
    });
  }

  findById(id) {
    const row = this.db.prepare("SELECT * FROM service_requests WHERE id = ?").get(id);
    return row ? this.toServiceRequest(row) : null;
  }

  // the id is generated by the database (AUTOINCREMENT), never supplied by the caller
  save(serviceRequest) {
    const result = this.db.prepare(
      `INSERT INTO service_requests (resident_id, service_type, description, date_requested, status)
       VALUES (?, ?, ?, ?, ?)`
    ).run(
      serviceRequest.residentId,
      serviceRequest.serviceType,
      serviceRequest.description,
      serviceRequest.dateRequested,
      serviceRequest.status
    );

    return this.findById(result.lastInsertRowid);
  }
}
